### ISSUE TITLE
No $EDITOR environment variable

### ISSUE THREAD

**Issue by bennettscience** [mgarrido/todo.txt-cli#4]
Where do you set the `$EDITOR` environment variable? I've tried editing your script plus `todo.sh` with `EDITOR=/Applications/Atom.app` with no luck. I've also tried editing the `todo.cfg` file.

I love the idea, I just can't put the last piece in place.

**Comment by bennettscience** [comment]
I didn't test quite enough. Adding a Terminal editor - `nano`, `vim`, etc, - as an `EDITOR` variable on line 8 got it going.

I'm still receiving an error after creating a note: `line 152: Contact: command not found`

**Comment by mgarrido** [comment]
You don't have to edit the script to set the EDITOR environment variable, you can do it in the shell, see https://askubuntu.com/a/432530

I don't know what means that "line 152" error, my script has only 150 lines.

**Comment by bennettscience** [comment]
Yeah, not sure what that is. Not a huge deal. Thanks.
